# Generated by Django 4.2.5 on 2025-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driving_license_cat',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license_num',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_registration_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='service_type',
            field=models.CharField(blank=True, choices=[('towing', 'Towing'), ('repair', 'Repair')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('assistant', 'Assistant')], default='client', max_length=10),
        ),
    ]
