# Generated by Django 4.2.5 on 2025-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_driving_license_cat_user_driving_license_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='23424233', max_length=20, unique=True),
        ),
    ]
