# Generated by Django 4.2.5 on 2025-04-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='driving_license_cat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driving_license_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driving_license_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vehicle_registration_num',
        ),
    ]
