# Generated by Django 4.2.5 on 2025-04-25 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_driving_license_cat_user_driving_license_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=10)),
                ('rating', models.SmallIntegerField(default=0)),
                ('distance_km', models.FloatField(default=0.0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances_as_assistant', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances_as_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='core_assist_status_629320_idx')],
            },
        ),
    ]
