# Generated by Django 4.2.5 on 2025-04-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_assistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
