# Generated by Django 4.2.5 on 2025-04-26 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_current_lat_user_current_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistances_as_assistant', to=settings.AUTH_USER_MODEL),
        ),
    ]
