# Generated by Django 4.2.5 on 2025-04-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_assistance_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
